### ISSUE TITLE
steam-mass-comment-bot errore

### ISSUE THREAD

**Issue by ErzaScarlets** [3urobeat/steam-mass-comment-bot#17]
Hi, I have such a mistake, could you help me please
![1](https://github.com/3urobeat/steam-mass-comment-bot/assets/130708127/5f1c3c8a-1178-4960-843f-3dc65f8fcf56)
![2](https://github.com/3urobeat/steam-mass-comment-bot/assets/130708127/03a3f814-ba3e-4ac8-a948-db4cec8cf34e)
![3](https://github.com/3urobeat/steam-mass-comment-bot/assets/130708127/db637fb4-fb5c-4d62-b065-935d35d2747e)

**Comment by ErzaScarlets** [comment]
![5](https://github.com/3urobeat/steam-mass-comment-bot/assets/130708127/102d8d0d-3ac7-4ba7-91f7-095e11feb7fa)

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue!  
You can ignore the NPM warnings in screenshot 2 & 3, they are meaningless and confusing for users.  
They appear when a library uses other outdated libraries and I need to wait for them to update their dependencies - whatever.  

The error in your first screenshot happens when the account you want to use is logged in somewhere else at the same time (as the error already precisely says).  
A Steam account can only be logged in once into SteamCommunity simultaneously, so please make sure you have closed your Steam Client or whatever else is trying to use that account at the same time.  
I could probably improve how these errors are presented to the user.

The error in your last screenshot looks like invalid profile/group links/IDs in your config. Can you post here what you configured there?

**Comment by ErzaScarlets** [comment]
[config.json](https://github.com/3urobeat/steam-mass-comment-bot/files/13795564/config.json)
![Screenshot](https://github.com/3urobeat/steam-mass-comment-bot/assets/130708127/b06d0ca5-71e3-4dea-bf67-09f5f92ab955)

**Comment by 3urobeat** [comment]
I'm not really sure what happened there tbh  
I have just now released Version 2.2.0 which changes how this works and adds support for commenting on sharedfiles & discussions as well.  
Please re-download the bot and try again, maybe this issue was fixed with it ^^

**Comment by ErzaScarlets** [comment]
Thanks everything is working
